sudo: required

language: python

services:
- docker
- postgresql

before_install:
- pip install docker-compose
- docker --version
- sudo service postgresql stop

script:
- make travis_compose_build
- make travis_compose_up
- make travis_compose_make_test
